language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - curl -SLv ftp://ftp.ncbi.nlm.nih.gov/blast/temp/model2taxid/taxidlineage.dmp -o src/data/taxidlineage.dmp
install: 
  - pip install -r src/requirements.txt
  - make -C src init_taxadb
script: 
  - make -C src check
